version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/examples"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
